version: "3.8"

services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PicturesDBConnectionString=Server=db;Database=PicturesDB;User=sa;Password=Your_password123;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - fullstack

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - fullstack

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

volumes:
  sqlserverdata:
